trigger:
- main

pool:
  name: Default  # Use your actual agent pool name

stages:
- stage: InstallAndTest
  jobs:
  - job: InstallJMeter
    steps:

    - task: PowerShell@2
      displayName: "Add Chocolatey to PATH and Install JMeter"
      inputs:
        targetType: 'inline'
        script: |
          $chocoPath = 'C:\ProgramData\chocolatey\bin'
          $env:Path += ";$chocoPath"
          choco install jmeter -y

    - task: PowerShell@2
      displayName: "Verify JMeter Installation"
      inputs:
        targetType: 'inline'
        script: |
          $jmeterBin = 'C:\ProgramData\chocolatey\lib\jmeter\tools\apache-jmeter-5.6.3\bin'
          $env:Path += ";$jmeterBin"
          jmeter -v

    - task: PowerShell@2
      displayName: "Run JMeter Test Plan"
      inputs:
        targetType: 'inline'
        script: |
          $jmeterBin = 'C:\ProgramData\chocolatey\lib\jmeter\tools\apache-jmeter-5.6.3\bin'
          $env:Path += ";$jmeterBin"
          jmeter -n -t tests/performance/sample_test.jmx -l results/result.jtl -e -o results/html

    - task: PublishBuildArtifacts@1
      displayName: "Publish JMeter HTML Report"
      inputs:
        PathtoPublish: 'results/html'
        ArtifactName: 'JMeterReport'
        publishLocation: 'Container'
